# Generated by Django 5.0.4 on 2024-04-26 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0002_remove_locations_empid_locations_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Locations', to='proj.employee'),
        ),
    ]
